### ISSUE TITLE
Is there going to be any future updates for this? 

### ISSUE THREAD

**Issue by bumbojumbo** [aKalisch/gosx-public-external#12]
The triggerbot needs some work (shoots to slow and misses a lot), also a toggle key menu with hotkeys so you can toggle walls, trigger, aimbot, ect active (press key once). I really appreciate your work, great job.

**Comment by ericek111** [comment]
You can contribute. :)

**Comment by bumbojumbo** [comment]
Very new to c++ only new how to do those two things which anyone with a brain can change, I wouldn't really know where to start.

**Comment by aKalisch** [comment]
As described in the readme. There will be no updates.
