### ISSUE TITLE
Legit Configs?

### ISSUE THREAD

**Issue by bumbojumbo** [aKalisch/gosx-public-external#13]
has anyone found a really good legit setting with this, I've made some modifications to the triggerbot so it shoots with less delay, also ive started working on keybinds.

**Comment by MyNameIsLebronJames** [comment]
Triggerbot doesn't seem to work for me?

**Comment by bumbojumbo** [comment]
Really? I mean the triggerbot isn't very reliable, but it does work. On
csgo console do bind CTRL +alt1 or whatever the alt thing is.

**Comment by MyNameIsLebronJames** [comment]
Oh, it works, but it's so bad, I have to hold CTRL to keep it shooting, and it's slow

**Comment by bumbojumbo** [comment]
You can bind it to whatever you want, but an external hack can only get so
good. Internal has more potential.
