### ISSUE TITLE
Full on Tutorial. (CLOSE)

### ISSUE THREAD

**Issue by Eggsdee** [aKalisch/gosx-public-external#15]
Hi.

Some people are not familiar with these things such as myself. 

Can we please get a rundown on how to run this. 

Steps that i've done - 
I've built the xcode 
I got the gosx excecutable. (+ the settings.ini)
Then dragged that gosx file into sudo -s 
Pressed enter while i was in a bot match. 
From that point, how do we enable features. There something about +alt1?? 

Thanks!

**Comment by bumbojumbo** [comment]
Bind FAVKEY +alt1 in the cs go console for triggerbot, bhop you set to true in settings.ini, if you don't know you have to open ini's with textedit usually. aimbot, noflash, ect are all in the settings.ini

**Comment by Eggsdee** [comment]
Hey Thank you very much for your response!!!
