### ISSUE TITLE
Triggerbot doesn't fire immediately when over an enemy?

### ISSUE THREAD

**Issue by roke-william** [aKalisch/gosx-public-external#17]
There is a way to change the quickness of shooting over other enemies? I've noticed that there is a large delay when hovering over an enemy and it does not shoot if you wave over them. Unlike the original aimtux, cheatsformac or aim ware, it shoots almost immediately. Not sure if it's an issue, or I'm missing something.

**Comment by aKalisch** [comment]
That's called delay and was added due to AC protection. You might remove the delay in https://github.com/aKalisch/gosx-public-external/blob/master/Engine/Features/TriggerBot.cpp#L93

Remember: this is external. So this type of hack is slower than internal.
