### ISSUE TITLE
Aimbot

### ISSUE THREAD

**Issue by Kazzaowo** [aKalisch/gosx-public-external#18]
How in the heck do i get rid of the dynamic aimbot and make it only go to the head? is dynamic easier and so only hs actually requires more code or is dynamic more difficult? any pointers to where to look to change the code would be great

thanks aKalisch!

**Comment by aKalisch** [comment]
https://github.com/aKalisch/gosx-public-external/blob/master/Engine/Features/AimHelper.cpp#L74
Replace `getBestBone(posOffset, locViewAngle, entity)` with `BONE_HEAD`

https://github.com/aKalisch/gosx-public-external/blob/master/Engine/Features/AimHelper.cpp#L135
Replace `getBestBone(posOffset, locViewAngle, entity)` with `BONE_HEAD`

**Comment by Kazzaowo** [comment]
how tf did i not see that smh thanks man
