### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by KazzaKING** [aKalisch/gosx-public-external#2]
![image](https://cloud.githubusercontent.com/assets/25977836/23331633/dc1d43ee-fba4-11e6-8fa2-bcca0b7ce342.png)

there seems to be an error when it tries to link the opengl etc frameworks; apparently the SDL2.framework is missing?

UPDATE: I have deleted the file and has now succeeded its build, i'm now testing the file.

UPDATE 2: Absolutely everything works fucking perfectly. You are a God amongst men, many kudos.

P.s: Not deleting issue as other people might stumble across this.

**Comment by KazzaKING** [comment]
I have deleted the file and has now succeeded its build, i'm now seeing if it works.

**Comment by swayamz** [comment]
do you know how to turn on triggerbot?

**Comment by ItzByZoneb** [comment]
I deleted the file framework and the build worked but when I wanted to open my hack the terminal said that it did not find csgo HELP ME

**Comment by KazzaKING** [comment]
@swayamz you bind triggerbot to an in game key, i have it to a button on the side of my mouse: "bind mouse5 +alt1" in console, +alt1 is what you need to bind it to.

@ItzByZoneb you have to type "sudo -s" into console first. then drag the hack into the terminal. "sudo -s" gives the terminal window and thus the hack root permission so it can read memory.

Please read on these programs and languages before giving up. Dont be a script kiddie; put as much effort in as possible so people take you seriously and youre not completely just using other peoples work without having knowledge yourself.

**Comment by CookinFood** [comment]
For some reason i cant get the triggerbot to work i can only get the esp

Like when i bind it in console it doesnt work please help.
