### ISSUE TITLE
How do I disable aimbot

### ISSUE THREAD

**Issue by Acornay** [aKalisch/gosx-public-external#7]
I have no idea how

**Comment by ericek111** [comment]
Modify `cFeatureManager::GetAimHelperThread` function: https://github.com/aKalisch/gosx-public-external/blob/master/Engine/FeatureManager/feature.cpp#L48

Change while(true) to while(false) manually (fastest and easiest) or bind it to a key, so you can toggle on-the-fly.

**Comment by aKalisch** [comment]
What heck... commenting code where an setting exists?

```
if(
           settings->GetHackenabled() &&
           settings->GetAimbot() // in the settings.ini on the Aimbot section is a setting called autoaim ... set it to false!
        ) {
            if(engine->GetEngineClient()->isInGame()) {
                g_cAimHelper->apply();
            }
        }
